/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChainHeight {
    #[serde(rename = "chain")]
    pub chain: String,
    #[serde(rename = "height")]
    pub height: i64,
}

impl ChainHeight {
    pub fn new(chain: String, height: i64) -> ChainHeight {
        ChainHeight {
            chain,
            height,
        }
    }
}


