/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvariantsResponse {
    #[serde(rename = "invariants", skip_serializing_if = "Option::is_none")]
    pub invariants: Option<Vec<String>>,
}

impl InvariantsResponse {
    pub fn new() -> InvariantsResponse {
        InvariantsResponse {
            invariants: None,
        }
    }
}


