/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricsResponse {
    #[serde(rename = "keygen", skip_serializing_if = "Option::is_none")]
    pub keygen: Option<Vec<crate::models::KeygenMetric>>,
    #[serde(rename = "keysign", skip_serializing_if = "Option::is_none")]
    pub keysign: Option<Box<crate::models::KeysignMetrics>>,
}

impl MetricsResponse {
    pub fn new() -> MetricsResponse {
        MetricsResponse {
            keygen: None,
            keysign: None,
        }
    }
}


