/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MimirVote {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i64>,
    #[serde(rename = "signer", skip_serializing_if = "Option::is_none")]
    pub signer: Option<String>,
}

impl MimirVote {
    pub fn new() -> MimirVote {
        MimirVote {
            key: None,
            value: None,
            signer: None,
        }
    }
}


