/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NodeBondProviders {
    /// node operator fee in basis points
    #[serde(rename = "node_operator_fee", skip_serializing_if = "Option::is_none")]
    pub node_operator_fee: Option<String>,
    #[serde(rename = "providers", skip_serializing_if = "Option::is_none")]
    pub providers: Option<Box<crate::models::NodeBondProvider>>,
}

impl NodeBondProviders {
    pub fn new() -> NodeBondProviders {
        NodeBondProviders {
            node_operator_fee: None,
            providers: None,
        }
    }
}


