/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NodePubKeySet {
    #[serde(rename = "secp256k1", skip_serializing_if = "Option::is_none")]
    pub secp256k1: Option<String>,
    #[serde(rename = "ed25519", skip_serializing_if = "Option::is_none")]
    pub ed25519: Option<String>,
}

impl NodePubKeySet {
    pub fn new() -> NodePubKeySet {
        NodePubKeySet {
            secp256k1: None,
            ed25519: None,
        }
    }
}


