/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NodePreflightStatus {
    /// the next status of the node
    #[serde(rename = "status")]
    pub status: String,
    /// the reason for the transition to the next status
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "code")]
    pub code: i64,
}

impl NodePreflightStatus {
    pub fn new(status: String, reason: String, code: i64) -> NodePreflightStatus {
        NodePreflightStatus {
            status,
            reason,
            code,
        }
    }
}


