/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QueueResponse {
    #[serde(rename = "swap")]
    pub swap: i64,
    /// number of signed outbound tx in the queue
    #[serde(rename = "outbound")]
    pub outbound: i64,
    #[serde(rename = "internal")]
    pub internal: i64,
    /// scheduled outbound value in RUNE
    #[serde(rename = "scheduled_outbound_value")]
    pub scheduled_outbound_value: String,
}

impl QueueResponse {
    pub fn new(swap: i64, outbound: i64, internal: i64, scheduled_outbound_value: String) -> QueueResponse {
        QueueResponse {
            swap,
            outbound,
            internal,
            scheduled_outbound_value,
        }
    }
}


