/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TxOutItem {
    #[serde(rename = "chain")]
    pub chain: String,
    #[serde(rename = "to_address")]
    pub to_address: String,
    #[serde(rename = "vault_pub_key", skip_serializing_if = "Option::is_none")]
    pub vault_pub_key: Option<String>,
    #[serde(rename = "coin")]
    pub coin: Box<crate::models::Coin>,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "max_gas")]
    pub max_gas: Vec<crate::models::Coin>,
    #[serde(rename = "gas_rate", skip_serializing_if = "Option::is_none")]
    pub gas_rate: Option<i64>,
    #[serde(rename = "in_hash", skip_serializing_if = "Option::is_none")]
    pub in_hash: Option<String>,
    #[serde(rename = "out_hash", skip_serializing_if = "Option::is_none")]
    pub out_hash: Option<String>,
    #[serde(rename = "height")]
    pub height: i64,
}

impl TxOutItem {
    pub fn new(chain: String, to_address: String, coin: crate::models::Coin, max_gas: Vec<crate::models::Coin>, height: i64) -> TxOutItem {
        TxOutItem {
            chain,
            to_address,
            vault_pub_key: None,
            coin: Box::new(coin),
            memo: None,
            max_gas,
            gas_rate: None,
            in_hash: None,
            out_hash: None,
            height,
        }
    }
}


