/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TxStagesResponseInboundFinalised {
    /// returns true if the inbound transaction has been finalised (THORChain agreeing it exists)
    #[serde(rename = "completed")]
    pub completed: bool,
}

impl TxStagesResponseInboundFinalised {
    pub fn new(completed: bool) -> TxStagesResponseInboundFinalised {
        TxStagesResponseInboundFinalised {
            completed,
        }
    }
}


