/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TxStagesResponseSwapStatusStreaming {
    /// how often each swap is made, in blocks
    #[serde(rename = "interval")]
    pub interval: i32,
    /// the total number of swaps in a streaming swaps
    #[serde(rename = "quantity")]
    pub quantity: i32,
    /// the amount of swap attempts so far
    #[serde(rename = "count")]
    pub count: i32,
}

impl TxStagesResponseSwapStatusStreaming {
    pub fn new(interval: i32, quantity: i32, count: i32) -> TxStagesResponseSwapStatusStreaming {
        TxStagesResponseSwapStatusStreaming {
            interval,
            quantity,
            count,
        }
    }
}


