/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TxStatusResponsePlannedOutTxsInner {
    #[serde(rename = "chain")]
    pub chain: String,
    #[serde(rename = "to_address")]
    pub to_address: String,
    #[serde(rename = "coin")]
    pub coin: Box<crate::models::Coin>,
    /// returns true if the planned transaction has a refund memo
    #[serde(rename = "refund")]
    pub refund: bool,
}

impl TxStatusResponsePlannedOutTxsInner {
    pub fn new(chain: String, to_address: String, coin: crate::models::Coin, refund: bool) -> TxStatusResponsePlannedOutTxsInner {
        TxStatusResponsePlannedOutTxsInner {
            chain,
            to_address,
            coin: Box::new(coin),
            refund,
        }
    }
}


