/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TxStagesResponse {
    #[serde(rename = "inbound_observed")]
    pub inbound_observed: Box<crate::models::TxStagesResponseInboundObserved>,
    #[serde(rename = "inbound_confirmation_counted", skip_serializing_if = "Option::is_none")]
    pub inbound_confirmation_counted: Option<Box<crate::models::TxStagesResponseInboundConfirmationCounted>>,
    #[serde(rename = "inbound_finalised", skip_serializing_if = "Option::is_none")]
    pub inbound_finalised: Option<Box<crate::models::TxStagesResponseInboundFinalised>>,
    #[serde(rename = "swap_status", skip_serializing_if = "Option::is_none")]
    pub swap_status: Option<Box<crate::models::TxStagesResponseSwapStatus>>,
    #[serde(rename = "swap_finalised", skip_serializing_if = "Option::is_none")]
    pub swap_finalised: Option<Box<crate::models::TxStagesResponseSwapFinalised>>,
    #[serde(rename = "outbound_delay", skip_serializing_if = "Option::is_none")]
    pub outbound_delay: Option<Box<crate::models::TxStagesResponseOutboundDelay>>,
    #[serde(rename = "outbound_signed", skip_serializing_if = "Option::is_none")]
    pub outbound_signed: Option<Box<crate::models::TxStagesResponseOutboundSigned>>,
}

impl TxStagesResponse {
    pub fn new(inbound_observed: crate::models::TxStagesResponseInboundObserved) -> TxStagesResponse {
        TxStagesResponse {
            inbound_observed: Box::new(inbound_observed),
            inbound_confirmation_counted: None,
            inbound_finalised: None,
            swap_status: None,
            swap_finalised: None,
            outbound_delay: None,
            outbound_signed: None,
        }
    }
}


