/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VersionResponse {
    /// current version
    #[serde(rename = "current")]
    pub current: String,
    /// next version (minimum version for a node to become Active)
    #[serde(rename = "next")]
    pub next: String,
    /// height at which the minimum joining version last changed
    #[serde(rename = "next_since_height", skip_serializing_if = "Option::is_none")]
    pub next_since_height: Option<i64>,
    /// querier version
    #[serde(rename = "querier")]
    pub querier: String,
}

impl VersionResponse {
    pub fn new(current: String, next: String, querier: String) -> VersionResponse {
        VersionResponse {
            current,
            next,
            next_since_height: None,
            querier,
        }
    }
}


