/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Borrower {
    #[serde(rename = "owner")]
    pub owner: String,
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "debt_issued")]
    pub debt_issued: String,
    #[serde(rename = "debt_repaid")]
    pub debt_repaid: String,
    #[serde(rename = "debt_current")]
    pub debt_current: String,
    #[serde(rename = "collateral_deposited")]
    pub collateral_deposited: String,
    #[serde(rename = "collateral_withdrawn")]
    pub collateral_withdrawn: String,
    #[serde(rename = "collateral_current")]
    pub collateral_current: String,
    #[serde(rename = "last_open_height")]
    pub last_open_height: i64,
    #[serde(rename = "last_repay_height")]
    pub last_repay_height: i64,
}

impl Borrower {
    pub fn new(owner: String, asset: String, debt_issued: String, debt_repaid: String, debt_current: String, collateral_deposited: String, collateral_withdrawn: String, collateral_current: String, last_open_height: i64, last_repay_height: i64) -> Borrower {
        Borrower {
            owner,
            asset,
            debt_issued,
            debt_repaid,
            debt_current,
            collateral_deposited,
            collateral_withdrawn,
            collateral_current,
            last_open_height,
            last_repay_height,
        }
    }
}


