/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConstantsResponse {
    #[serde(rename = "int_64_values", skip_serializing_if = "Option::is_none")]
    pub int_64_values: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "bool_values", skip_serializing_if = "Option::is_none")]
    pub bool_values: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "string_values", skip_serializing_if = "Option::is_none")]
    pub string_values: Option<::std::collections::HashMap<String, String>>,
}

impl ConstantsResponse {
    pub fn new() -> ConstantsResponse {
        ConstantsResponse {
            int_64_values: None,
            bool_values: None,
            string_values: None,
        }
    }
}


