/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvariantResponse {
    /// The name of the invariant.
    #[serde(rename = "invariant")]
    pub invariant: String,
    /// Returns true if the invariant is broken.
    #[serde(rename = "broken")]
    pub broken: bool,
    /// Informative message about the invariant result.
    #[serde(rename = "msg")]
    pub msg: Vec<String>,
}

impl InvariantResponse {
    pub fn new(invariant: String, broken: bool, msg: Vec<String>) -> InvariantResponse {
        InvariantResponse {
            invariant,
            broken,
            msg,
        }
    }
}


