/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KeysignInfo {
    /// the block(s) in which a tx out item is scheduled to be signed and moved from the scheduled outbound queue to the outbound queue
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
    #[serde(rename = "tx_array")]
    pub tx_array: Vec<crate::models::TxOutItem>,
}

impl KeysignInfo {
    pub fn new(tx_array: Vec<crate::models::TxOutItem>) -> KeysignInfo {
        KeysignInfo {
            height: None,
            tx_array,
        }
    }
}


