/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KeysignResponse {
    #[serde(rename = "keysign", skip_serializing_if = "Option::is_none")]
    pub keysign: Option<Box<crate::models::KeysignInfo>>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
}

impl KeysignResponse {
    pub fn new() -> KeysignResponse {
        KeysignResponse {
            keysign: None,
            signature: None,
        }
    }
}


