/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KeysignMetrics {
    #[serde(rename = "tx_id", skip_serializing_if = "Option::is_none")]
    pub tx_id: Option<String>,
    #[serde(rename = "node_tss_times", skip_serializing_if = "Option::is_none")]
    pub node_tss_times: Option<Vec<crate::models::TssMetric>>,
}

impl KeysignMetrics {
    pub fn new() -> KeysignMetrics {
        KeysignMetrics {
            tx_id: None,
            node_tss_times: None,
        }
    }
}


