/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LastBlock {
    #[serde(rename = "chain")]
    pub chain: String,
    #[serde(rename = "last_observed_in")]
    pub last_observed_in: i64,
    #[serde(rename = "last_signed_out")]
    pub last_signed_out: i64,
    #[serde(rename = "thorchain")]
    pub thorchain: i64,
}

impl LastBlock {
    pub fn new(chain: String, last_observed_in: i64, last_signed_out: i64, thorchain: i64) -> LastBlock {
        LastBlock {
            chain,
            last_observed_in,
            last_signed_out,
            thorchain,
        }
    }
}


