/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MimirNodesResponse {
    #[serde(rename = "mimirs", skip_serializing_if = "Option::is_none")]
    pub mimirs: Option<Vec<crate::models::MimirVote>>,
}

impl MimirNodesResponse {
    pub fn new() -> MimirNodesResponse {
        MimirNodesResponse {
            mimirs: None,
        }
    }
}


