/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NodeJail {
    #[serde(rename = "release_height", skip_serializing_if = "Option::is_none")]
    pub release_height: Option<i64>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl NodeJail {
    pub fn new() -> NodeJail {
        NodeJail {
            release_height: None,
            reason: None,
        }
    }
}


