/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Ping {
    #[serde(rename = "ping", skip_serializing_if = "Option::is_none")]
    pub ping: Option<String>,
}

impl Ping {
    pub fn new() -> Ping {
        Ping {
            ping: None,
        }
    }
}


