/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PolResponse {
    /// total amount of RUNE deposited into the pools
    #[serde(rename = "rune_deposited")]
    pub rune_deposited: String,
    /// total amount of RUNE withdrawn from the pools
    #[serde(rename = "rune_withdrawn")]
    pub rune_withdrawn: String,
    /// total value of protocol's LP position in RUNE value
    #[serde(rename = "value")]
    pub value: String,
    /// profit and loss of protocol owned liquidity
    #[serde(rename = "pnl")]
    pub pnl: String,
    /// current amount of rune deposited
    #[serde(rename = "current_deposit")]
    pub current_deposit: String,
}

impl PolResponse {
    pub fn new(rune_deposited: String, rune_withdrawn: String, value: String, pnl: String, current_deposit: String) -> PolResponse {
        PolResponse {
            rune_deposited,
            rune_withdrawn,
            value,
            pnl,
            current_deposit,
        }
    }
}


