/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TssKeysignMetric {
    #[serde(rename = "tx_id", skip_serializing_if = "Option::is_none")]
    pub tx_id: Option<String>,
    #[serde(rename = "node_tss_times")]
    pub node_tss_times: Vec<crate::models::TssMetric>,
}

impl TssKeysignMetric {
    pub fn new(node_tss_times: Vec<crate::models::TssMetric>) -> TssKeysignMetric {
        TssKeysignMetric {
            tx_id: None,
            node_tss_times,
        }
    }
}


