/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TxDetailsResponse {
    #[serde(rename = "tx_id", skip_serializing_if = "Option::is_none")]
    pub tx_id: Option<String>,
    #[serde(rename = "tx")]
    pub tx: Box<crate::models::ObservedTx>,
    #[serde(rename = "txs")]
    pub txs: Vec<crate::models::ObservedTx>,
    #[serde(rename = "actions")]
    pub actions: Vec<crate::models::TxOutItem>,
    #[serde(rename = "out_txs")]
    pub out_txs: Vec<crate::models::Tx>,
    /// the thorchain height at which the inbound reached consensus
    #[serde(rename = "consensus_height", skip_serializing_if = "Option::is_none")]
    pub consensus_height: Option<i64>,
    /// the thorchain height at which the outbound was finalised
    #[serde(rename = "finalised_height", skip_serializing_if = "Option::is_none")]
    pub finalised_height: Option<i64>,
    #[serde(rename = "updated_vault", skip_serializing_if = "Option::is_none")]
    pub updated_vault: Option<bool>,
    #[serde(rename = "reverted", skip_serializing_if = "Option::is_none")]
    pub reverted: Option<bool>,
    /// the thorchain height for which the outbound was scheduled
    #[serde(rename = "outbound_height", skip_serializing_if = "Option::is_none")]
    pub outbound_height: Option<i64>,
}

impl TxDetailsResponse {
    pub fn new(tx: crate::models::ObservedTx, txs: Vec<crate::models::ObservedTx>, actions: Vec<crate::models::TxOutItem>, out_txs: Vec<crate::models::Tx>) -> TxDetailsResponse {
        TxDetailsResponse {
            tx_id: None,
            tx: Box::new(tx),
            txs,
            actions,
            out_txs,
            consensus_height: None,
            finalised_height: None,
            updated_vault: None,
            reverted: None,
            outbound_height: None,
        }
    }
}


