/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TxStagesResponseSwapFinalised {
    /// (to be deprecated in favor of swap_status) returns true if an inbound transaction's swap (successful or refunded) is no longer pending
    #[serde(rename = "completed")]
    pub completed: bool,
}

impl TxStagesResponseSwapFinalised {
    pub fn new(completed: bool) -> TxStagesResponseSwapFinalised {
        TxStagesResponseSwapFinalised {
            completed,
        }
    }
}


