/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TxStagesResponseOutboundDelay {
    /// the number of remaining THORChain blocks the outbound will be delayed
    #[serde(rename = "remaining_delay_blocks", skip_serializing_if = "Option::is_none")]
    pub remaining_delay_blocks: Option<i64>,
    /// the estimated remaining seconds of the outbound delay before it will be sent
    #[serde(rename = "remaining_delay_seconds", skip_serializing_if = "Option::is_none")]
    pub remaining_delay_seconds: Option<i64>,
    /// returns true if no transaction outbound delay remains
    #[serde(rename = "completed")]
    pub completed: bool,
}

impl TxStagesResponseOutboundDelay {
    pub fn new(completed: bool) -> TxStagesResponseOutboundDelay {
        TxStagesResponseOutboundDelay {
            remaining_delay_blocks: None,
            remaining_delay_seconds: None,
            completed,
        }
    }
}


