/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TxStagesResponseSwapStatus {
    /// true when awaiting a swap
    #[serde(rename = "pending")]
    pub pending: bool,
    #[serde(rename = "streaming", skip_serializing_if = "Option::is_none")]
    pub streaming: Option<Box<crate::models::TxStagesResponseSwapStatusStreaming>>,
}

impl TxStagesResponseSwapStatus {
    pub fn new(pending: bool) -> TxStagesResponseSwapStatus {
        TxStagesResponseSwapStatus {
            pending,
            streaming: None,
        }
    }
}


