/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VaultPubkeysResponse {
    #[serde(rename = "asgard")]
    pub asgard: Vec<crate::models::VaultInfo>,
    #[serde(rename = "yggdrasil")]
    pub yggdrasil: Vec<crate::models::VaultInfo>,
    #[serde(rename = "inactive")]
    pub inactive: Vec<crate::models::VaultInfo>,
}

impl VaultPubkeysResponse {
    pub fn new(asgard: Vec<crate::models::VaultInfo>, yggdrasil: Vec<crate::models::VaultInfo>, inactive: Vec<crate::models::VaultInfo>) -> VaultPubkeysResponse {
        VaultPubkeysResponse {
            asgard,
            yggdrasil,
            inactive,
        }
    }
}


