/*
 * Thornode API
 *
 * Thornode REST API.
 *
 * The version of the OpenAPI document: 1.119.0
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VaultRouter {
    #[serde(rename = "chain", skip_serializing_if = "Option::is_none")]
    pub chain: Option<String>,
    #[serde(rename = "router", skip_serializing_if = "Option::is_none")]
    pub router: Option<String>,
}

impl VaultRouter {
    pub fn new() -> VaultRouter {
        VaultRouter {
            chain: None,
            router: None,
        }
    }
}


